// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_hPfxxJn9z1fBGYJjgLXsxZp-pzPwrrE',
    appId: '1:356990032495:web:ba2844c2f6961077670b9a',
    messagingSenderId: '356990032495',
    projectId: 'inform-me-414118',
    authDomain: 'inform-me-414118.firebaseapp.com',
    storageBucket: 'inform-me-414118.appspot.com',
    measurementId: 'G-6H81DJ657V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3tBdf4SNU9ZvtcmBrhS7q507DuP-TPcw',
    appId: '1:356990032495:android:81c34c902d01e7f3670b9a',
    messagingSenderId: '356990032495',
    projectId: 'inform-me-414118',
    storageBucket: 'inform-me-414118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-wJhts3QHeoFmvIhU7W79R0GwWahOsuI',
    appId: '1:356990032495:ios:c142ab7fd150dc8f670b9a',
    messagingSenderId: '356990032495',
    projectId: 'inform-me-414118',
    storageBucket: 'inform-me-414118.appspot.com',
    iosClientId: '356990032495-4rs0a4r02rtua3er9795q0q8bk6ppjtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.informme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-wJhts3QHeoFmvIhU7W79R0GwWahOsuI',
    appId: '1:356990032495:ios:05dd7befbc72ad84670b9a',
    messagingSenderId: '356990032495',
    projectId: 'inform-me-414118',
    storageBucket: 'inform-me-414118.appspot.com',
    iosClientId: '356990032495-k3kinb55jlb8511davcipr0v846h02c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.informme.RunnerTests',
  );
}
